# values.yaml
cluster: ${cluster_name}
dnsZone: ${dns_zone}
kubernetesVersion: ${kubernetes_version}
bucket: ${state_bucket}
nodeImage: ${node_image}

vpc:
  id: ${vpc_id}
  cidr: ${vpc_cidr}
  zone: ${region}

privateSubnets:
${private_subnets}

publicSubnets:
${public_subnets}

nodes:
${nodes}

addons:
${addons}

master:
  instanceType: ${master_node_type}
  role: server
